Repository sehlen-bsi/botan-docs, pull requests merged in 2023-07, with the labels that each got.

#17 Describe the planned Audit Process based on Pull Requests and Master-Commits
  audit_method/src/01_change_tracking.rst
  audit_method/src/06_summary.rst
  audit_method/src/90_references.rst
Labels: auditmethod

#8 XMSS Parameter sets and key gen from NIST SP.800-208
  cryptodoc/src/00_00_preface.rst
  cryptodoc/src/00_01_changelog.rst
  cryptodoc/src/06_pubkey_key_generation.rst
  cryptodoc/src/08_signatures.rst
  cryptodoc/src/90_bibliographie.rst
Labels: cryptodoc

#68 Audit: Code and Compiler Chores (3.1.0)
  audit_report/3.1.0/changes/topics/code_chores.yml
  audit_report/3.1.0/changes/topics/compiler_chores.yml
Labels: auditreport

#77 Audit: Update patch coverage to Botan 3.1.0
  audit_report/3.1.0/changes/config.yml
  audit_report/3.1.0/changes/topics/auxiliary_scripts.yml
  audit_report/3.1.0/changes/topics/build_system.yml
  audit_report/3.1.0/changes/topics/ci.yml
  audit_report/3.1.0/changes/topics/clang_format.yml
  audit_report/3.1.0/changes/topics/code_chores.yml
  audit_report/3.1.0/changes/topics/documentation.yml
  audit_report/3.1.0/changes/topics/fixes.yml
  audit_report/3.1.0/changes/topics/release.yml
  audit_report/3.1.0/changes/topics/sphincsplus.yml
  audit_report/3.1.0/changes/topics/test_framework.yml
  audit_report/3.1.0/changes/topics/tls.yml
Labels: auditreport

#76 Log GitHub API Rate Limit and Cache Hit Rate
  .github/workflows/ci.yml
  audit_generator/audit.py
  audit_generator/genaudit/cache.py
  audit_generator/genaudit/repo.py
Labels: auditreport

#66 Audit: Auxiliary Scripts, CI, Build System, and Test Framework
  audit_report/3.1.0/changes/topics/auxiliary_scripts.yml
  audit_report/3.1.0/changes/topics/build_system.yml
  audit_report/3.1.0/changes/topics/ci.yml
  audit_report/3.1.0/changes/topics/cli.yml
  audit_report/3.1.0/changes/topics/test_framework.yml
Labels: auditreport

#64 Audit: CLI, FFI, and Python Wrapper (3.1.0)
  audit_report/3.1.0/changes/topics/cli.yml
  audit_report/3.1.0/changes/topics/ffi.yml
  audit_report/3.1.0/changes/topics/python_wrapper.yml
Labels: auditreport

#79 FIX: Store cache if building fails due to rate limit
  .github/scripts/query_rate_limit.sh
  .github/workflows/ci.yml
  audit_generator/audit.py
Labels: auditreport

#81 Audit: Build System / Test Framework
  audit_report/3.1.0/changes/topics/build_system.yml
  audit_report/3.1.0/changes/topics/test_framework.yml
Labels: auditreport

#80 Final 3.1.0 Audit: TLS, SPHINCS+, and Fixes
  audit_report/3.1.0/changes/topics/fixes.yml
  audit_report/3.1.0/changes/topics/sphincsplus.yml
  audit_report/3.1.0/changes/topics/tls.yml
Labels: auditreport

#78 Final 3.1.0 Audit: Auxiliary Scripts, CI, and Clang Format
  audit_report/3.1.0/changes/topics/auxiliary_scripts.yml
  audit_report/3.1.0/changes/topics/ci.yml
  audit_report/3.1.0/changes/topics/clang_format.yml
Labels: auditreport

#84 Audit: Additional patches for Botan 3.1.1
  audit_generator/genaudit/repo.py
  audit_report/3.1.0/changes/config.yml
  audit_report/3.1.0/changes/topics/ci.yml
  audit_report/3.1.0/changes/topics/fixes.yml
  audit_report/3.1.0/changes/topics/release.yml
Labels: auditreport

#83 Audit: Documentation / Release Notes
  audit_report/3.1.0/changes/topics/documentation.yml
  audit_report/3.1.0/changes/topics/release.yml
  audit_report/3.1.0/changes/topics/sphincsplus.yml
Labels: auditreport

#63 Audit: Additions, Fixes, and Optimization (3.1.0)
  audit_report/3.1.0/changes/topics/additions.yml
  audit_report/3.1.0/changes/topics/fixes.yml
  audit_report/3.1.0/changes/topics/optimization.yml
Labels: auditreport

#86 Audit: Final patch review
  audit_report/3.1.0/changes/topics/release.yml
Labels: auditreport

#69 Cryptodoc: Update RNG info
  cryptodoc/src/09_rng.rst
Labels: cryptodoc

#11 Add hash truncation in ECKCDSA
  cryptodoc/src/08_signatures.rst
  cryptodoc/src/90_bibliographie.rst
Labels: enhancement, cryptodoc

#72 Documentation: BLAKE2b
  cryptodoc/src/01_hash.rst
  cryptodoc/src/90_bibliographie.rst
Labels: cryptodoc

#92 Doc: Migrate the Architecture Overview
  .github/workflows/ci.yml
  architecture/Makefile
  architecture/README.md
  architecture/requirements-dev.in
  architecture/requirements-dev.txt
  architecture/requirements.in
  architecture/requirements.txt
  architecture/src/01_architecture.rst
  architecture/src/conf.py
  architecture/src/custom.sty
  architecture/src/index.rst
Labels: architecture

#90 Add Argon2 to cryptodoc and audit
  audit_report/3.1.0/src/01_method.rst
  cryptodoc/src/13_pbkdf.rst
  cryptodoc/src/90_bibliographie.rst
  cryptodoc/src/index.rst
Labels: cryptodoc, auditreport

#47 Testspec: SPHINCS+
  testspec/src/14_pubkey_sig.rst
  testspec/src/conf.py
Labels: testspec

#91 Testspec: Add new algorithms
  testspec/src/05_hash.rst
  testspec/src/06_kdf.rst
  testspec/src/09_pbkdf.rst
Labels: testspec

#13 Add Dilithium Documentation
  cryptodoc/src/06_pubkey_key_generation.rst
  cryptodoc/src/08_signatures.rst
  cryptodoc/src/90_bibliographie.rst
Labels: cryptodoc

#25 Add SPHINCS+ Documentation
  cryptodoc/src/06_pubkey_key_generation.rst
  cryptodoc/src/08_signatures.rst
  cryptodoc/src/90_bibliographie.rst
  cryptodoc/src/conf.py
Labels: cryptodoc

#93 Architecture: Updates for Botan 3.1.1
  architecture/src/01_architecture.rst
  architecture/src/conf.py
Labels: architecture

#89 Botan 3.1.1 Audit Report Document
  audit_generator/genaudit/audit.py
  audit_generator/genaudit/render.py
  audit_generator/genaudit/templates/index.rst
  audit_report/3.1.0/changes/config.yml
  audit_report/3.1.0/src/00_00_preface.rst
  audit_report/3.1.0/src/00_09_introduction.rst
  audit_report/3.1.0/src/01_generic_changes.rst
  audit_report/3.1.0/src/01_method.rst
  audit_report/3.1.0/src/02_security_issues.rst
  audit_report/3.1.0/src/03_side_channels.rst
  audit_report/3.1.0/src/04_testsuite.rst
  audit_report/3.1.0/src/05_documents.rst
  audit_report/3.1.0/src/06_summary.rst
  audit_report/3.1.0/src/07_bibliography.rst
  audit_report/3.1.0/src/index.rst
Labels: auditreport

#96 FIX: Headline is needed in each chapter when building HTML
  audit_report/3.1.0/src/07_bibliography.rst
Labels: auditreport

#100 Pull the Botan target info from a central config file
  .github/actions/setup-environment/action.yml
  .github/environment/botan.env
  .github/scripts/read_environment.py
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#102 Move 'Source Archive' job to release workflow
  .github/scripts/tarball.py
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: enhancement

#106 FIX: Environment Configuration on Windows
  .github/actions/setup-environment/action.yml
Labels: bug

#99 Side-Channel Reports: XMSS, Kyber, Dilithium
  docs/audit_report/src/00_00_preface.rst
  docs/audit_report/src/03_side_channels.rst
  docs/audit_report/src/03_testsuite.rst
  docs/audit_report/src/04_documents.rst
  docs/audit_report/src/05_summary.rst
  docs/audit_report/src/06_bibliography.rst
  docs/audit_report/src/07_bibliography.rst
  docs/audit_report/src/conf.py
  docs/audit_report/src/index.rst
  docs/audit_report/src/side_channels/00_introduction.rst
  docs/audit_report/src/side_channels/01_data.rst
  docs/audit_report/src/side_channels/02_01_kyber.rst
  docs/audit_report/src/side_channels/02_02_dilithium.rst
  docs/audit_report/src/side_channels/02_03_xmss.rst
  docs/audit_report/src/side_channels/02_results.rst
  docs/audit_report/src/side_channels/img/cflow-leak.png
  docs/audit_report/src/side_channels/img/data-leak.png
  docs/audit_report/src/side_channels/img/data-phases.png
  docs/audit_report/src/side_channels/img/dilithium-pseudo-code.png
  docs/audit_report/src/side_channels/index.rst
Labels: auditreport

#111 Chore: Make audit-chapters start on new pages
  tools/genaudit/genaudit/templates/topic.rst
Labels: auditreport

#110 Restructure Asymmetric Algorithm Chapters in Cryptodoc.
  docs/cryptodoc/src/00_01_changelog.rst
  docs/cryptodoc/src/04_prim_generation.rst
  docs/cryptodoc/src/05_00_pubkey.rst
  docs/cryptodoc/src/05_01_dh.rst
  docs/cryptodoc/src/05_02_dsa.rst
  docs/cryptodoc/src/05_03_ecc.rst
  docs/cryptodoc/src/05_04_rsa.rst
  docs/cryptodoc/src/05_05_xmss.rst
  docs/cryptodoc/src/05_06_spx.rst
  docs/cryptodoc/src/05_07_dilithium.rst
  docs/cryptodoc/src/05_08_kyber.rst
  docs/cryptodoc/src/06_hpke.rst
  docs/cryptodoc/src/06_pubkey_key_generation.rst
  docs/cryptodoc/src/07_pubkey.rst
  docs/cryptodoc/src/07_rng.rst
  docs/cryptodoc/src/08_entropy.rst
  docs/cryptodoc/src/08_signatures.rst
  docs/cryptodoc/src/09_x509.rst
  docs/cryptodoc/src/10_kdf.rst
  docs/cryptodoc/src/11_pbkdf.rst
  docs/cryptodoc/src/index.rst
Labels: cryptodoc
