Repository sehlen-bsi/botan-docs, pull requests merged in 2024-06, with the labels that each got.

#141 HSS/LMS Testspecification
  docs/testspec/src/14_pubkey_sig.rst
Labels: testspec

#140 HSS/LMS Crypto Documentation
  docs/cryptodoc/src/00_01_changelog.rst
  docs/cryptodoc/src/05_00_pubkey.rst
  docs/cryptodoc/src/05_06_hss_lms.rst
  docs/cryptodoc/src/05_07_spx.rst
  docs/cryptodoc/src/05_08_dilithium.rst
  docs/cryptodoc/src/05_09_kyber.rst
  docs/cryptodoc/src/05_10_frodokem.rst
  docs/cryptodoc/src/90_bibliographie.rst
Labels: cryptodoc

#153 HSS/LMS: Side Channel Analysis
  docs/audit_report/src/06_bibliography.rst
  docs/audit_report/src/side_channels/01_00_results.rst
  docs/audit_report/src/side_channels/01_01_lms.rst
Labels: auditreport

#217 Chore: update python dependencies
  .github/workflows/ci.yml
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  tools/auditinfo/poetry.lock
  tools/auditupdate/poetry.lock
  tools/auditutils/poetry.lock
  tools/genaudit/poetry.lock
  tools/sourceref/poetry.lock
  tools/tarball_checker/poetry.lock
Labels: chore

#219 Double-check crypto documentation of ECC
  docs/cryptodoc/src/05_03_ecc.rst
Labels: cryptodoc

#218 Chore: Use poetry for dependency mgmt only
  docs/architecture/pyproject.toml
  docs/audit_method/pyproject.toml
  docs/audit_report/pyproject.toml
  docs/cryptodoc/pyproject.toml
  docs/testreport/pyproject.toml
  docs/testspec/pyproject.toml
Labels: chore

#220 FIX: auto-update bot has to run on Ubuntu 24.04
  .github/workflows/auto-update.yml
Labels: bug

#222 Update poetry dependencies
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  tools/auditupdate/poetry.lock
  tools/genaudit/poetry.lock
  tools/sourceref/poetry.lock
Labels: chore
