Repository sehlen-bsi/botan-docs, pull requests merged in 2024-01, with the labels that each got.

#173 Mention TLS-Anvil in the test spec document
  docs/testspec/src/16_tls.rst
Labels: testspec

#157 FrodoKEM: Test Specification
  docs/testspec/src/12_pubkey_kem.rst
Labels: testreport

#175 FrodoKEM: Side Channel Analysis
  docs/audit_report/src/06_bibliography.rst
  docs/audit_report/src/side_channels/01_00_results.rst
  docs/audit_report/src/side_channels/01_02_frodokem.rst
Labels: auditreport
