Repository sehlen-bsi/botan-docs, pull requests merged in 2024-02, with the labels that each got.

#188 Feature: `:srcref:` can deep-link to specific source lines
  docs/cryptodoc/src/05_08_kyber.rst
  tools/sourceref/sourceref/__init__.py
  tools/sourceref/sourceref/role.py
Labels: enhancement

#191 Chore: Update dependencies
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  internal/update_poetry.sh
  tools/auditupdate/poetry.lock
  tools/genaudit/poetry.lock
  tools/sourceref/poetry.lock
Labels: chore

#117 FrodoKEM Cryptodoc
  docs/cryptodoc/src/05_00_pubkey.rst
  docs/cryptodoc/src/05_09_frodokem.rst
  docs/cryptodoc/src/90_bibliographie.rst
Labels: cryptodoc

#190 Cryptodoc: add BLAKE2s
  docs/cryptodoc/src/01_hash.rst
Labels: cryptodoc

#192 Chore: Some deep links in the PQC algorithms
  docs/cryptodoc/src/05_05_xmss.rst
  docs/cryptodoc/src/05_06_spx.rst
  docs/cryptodoc/src/05_07_dilithium.rst
  docs/cryptodoc/src/05_08_kyber.rst
Labels: cryptodoc

#197 FIX: (re-)create topic file directory
  tools/auditupdate/auditupdate/cli.py
Labels: bug

#198 Chore: Update Things
  .github/actions/setup-build-agent/action.yml
  .github/workflows/auto-update.yml
  .github/workflows/ci.yml
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  tools/auditupdate/poetry.lock
  tools/genaudit/poetry.lock
Labels: enhancement
