Repository sehlen-bsi/botan-docs, pull requests merged in 2024-10, with the labels that each got.

#240 Update poetry Dependencies
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  tools/auditinfo/poetry.lock
  tools/auditupdate/poetry.lock
  tools/genaudit/poetry.lock
  tools/sourceref/poetry.lock
  tools/tarball_checker/poetry.lock
Labels: chore

#246 Audit: 'Additions' and 'CI'
  docs/audit_report/changes/topics/additions.yml
  docs/audit_report/changes/topics/continuous_integration.yml
  docs/audit_report/changes/topics/fixes.yml
Labels: auditreport

#254 Audit: Botan 3.6.1 patches + Some missing annotations
  config/botan.env
  docs/audit_report/changes/topics/chore.yml
  docs/audit_report/changes/topics/fixes.yml
  docs/audit_report/changes/topics/pcurves.yml
  docs/audit_report/changes/topics/pqc.yml
  docs/audit_report/changes/topics/release.yml
  docs/audit_report/changes/topics/tls.yml
  tools/auditupdate/README.md
  tools/auditupdate/auditupdate/cli.py
  tools/genaudit/genaudit/repo.py
Labels: auditreport

#241 Testspec Update: ML-KEM, ML-DSA and SLH-DSA
  docs/testspec/src/12_pubkey_kem.rst
  docs/testspec/src/14_pubkey_sig.rst
Labels: testspec

#257 Enable :srcref: in audit report document
  .github/workflows/ci.yml
  docs/audit_report/src/conf.py
Labels: auditreport, chore
