Repository sehlen-bsi/botan-docs, pull requests merged in 2025-03, with the labels that each got.

#270 Audit: Build System Changes
  docs/audit_report/changes/topics/build.yml
Labels: auditreport

#272 Audit: Removals and Deprecations
  docs/audit_report/changes/topics/removals.yml
Labels: auditreport

#275 Audit: Chores
  docs/audit_report/changes/topics/chore.yml
  docs/audit_report/changes/topics/ci.yml
  docs/audit_report/changes/topics/cli.yml
Labels: auditreport

#274 Audit: Test and Continuous Integration Updates
  docs/audit_report/changes/topics/ci.yml
  docs/audit_report/changes/topics/fixes.yml
  docs/audit_report/changes/topics/tests.yml
Labels: auditreport

#273 Audit: Fixes
  docs/audit_report/changes/topics/ci.yml
  docs/audit_report/changes/topics/fixes.yml
Labels: auditreport

#277 Audit: ECC optimizations
  docs/audit_report/changes/topics/pcurve.yml
  docs/audit_report/src/06_bibliography.rst
Labels: auditreport

#280 Update poetry dependencies
  docs/architecture/poetry.lock
  docs/audit_method/poetry.lock
  docs/audit_report/poetry.lock
  docs/cryptodoc/poetry.lock
  docs/testreport/poetry.lock
  docs/testspec/poetry.lock
  tools/auditupdate/poetry.lock
  tools/genaudit/poetry.lock
  tools/sourceref/poetry.lock
Labels: chore

#278 3.7.1 Audit: Optimizations
  docs/audit_report/changes/topics/optimizations.yml
  docs/cryptodoc/src/05_04_rsa.rst
  docs/cryptodoc/src/90_bibliographie.rst
  tools/auditinfo/auditinfo/document.py
Labels: cryptodoc, auditreport

#271 Audit: Updates to the Documentation
  docs/audit_report/changes/topics/doc_release.yml
  docs/audit_report/changes/topics/documentation.yml
  docs/audit_report/changes/topics/pcurve.yml
Labels: auditreport

#281 Final touches for the audit report
  docs/audit_report/changes/topics/additions.yml
  docs/audit_report/changes/topics/build.yml
  docs/audit_report/changes/topics/chore.yml
  docs/audit_report/changes/topics/ci.yml
  docs/audit_report/changes/topics/fixes.yml
  docs/audit_report/changes/topics/optimizations.yml
  docs/audit_report/changes/topics/pcurve.yml
Labels: auditreport

#283 Allow printing 'skipped' modules in the audited_modules_list.py helper
  docs/audit_report/scripts/audited_modules_list.py
Labels: chore

#285 Rebase to Rohde-Schwarz/botan for 3.7.1-RSCS1
  .github/resources/rene-commit-signing-key.gpg
  .github/workflows/ci.yml
  config/botan.env
Labels: release
